image: docker:20.10

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10-dind

stages:
  - build
  - push
  - test

before_script:
  - docker info

build:
  stage: build
  script:
   - docker build -f Dockerfile -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest .
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest dhcp-helper -v

push_to_dockerhub:
 stage: push
 only:
   - master
 script:
   - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
   # ans latest
   - docker build -f Dockerfile -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest .
   # summary
   - docker images
   # push image
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest

test_docker_images:
 stage: test
 only:
   - master
 script:
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest dhcp-helper -v
